### ISSUE TITLE
数据集名称不对问题

### ISSUE THREAD

**Issue by xuchenxing** [datatang-ailab/aidatatang_200zh#2]
代码中下载数据集的链接是：
downloading data from www.openslr.org/resources/62/aidatatang_200zh.tgz.
但是报404错误，我查了下openslr上有200.zip的下载链接， 这两个是一样的吗？

**Comment by andy2301** [comment]
1. openslr上的200.zip文件大小和local/download_and_untar.sh中期待的文件大小不一样。
2. 下载200.zip解压缩后，没有看到local/aidatatang_data_prep.sh 期待的corpus和transcript这2个文件夹，也没有分成train, dev, test子文件夹

麻烦 @DatatangAI 帮忙看看?

**Comment by DatatangAI** [comment]
@xuchenxing 不好意思，刚看到您反应的问题。是这样的，目前openslr上SLR62存放的数据（200.zip）是本实验用到的基础数据集，我在进行本实验时对基础数据集（200.zip）中的标注文件做了分词，并根据分词后的文本生成了transcript文件，另一个改动是，我将200.zip数据集按照7：1：2的比例随机划分成了训练集、验证集和测试集。目前我正在联系openslr更新数据集，很快其将会替换成新的数据。
另外，@andy2301，你们也可以访问 https://www.datatang.com/webfront/opensource.html 下载到本实验用的数据。

**Comment by andy2301** [comment]
@DatatangAI 了解。请问是否可以把改动后的脚本和transcript文件打包放在github或者作为临时附件放在这个讨论区里? 非常感谢！

**Comment by DatatangAI** [comment]
@andy2301 所有音频及其对应的分词后的转录文本已经更新在data/aidatatang_200_zh_transcript.txt里了，由于数据是随机划分的，因此你可以设计程序实现它或者从上面的网址中获取到全部数据。

**Comment by xuchenxing** [comment]
@DatatangAI 你好，感谢你的回复，我按你的方法去网站上申请，然后收到了一封下载链接的邮件， 但是这个链接指向的下载内容，还是老的200.zip的内容，没有script。 然后我又看了下openslr也还没有更新。 
邮件上的下载链接是这个：
以下是    精选【200小时中文普通话语音数据】 下载链接：
    http://bj-oss-data-04.oss-cn-beijing.aliyuncs.com/%E5%BC%80%E6%BA%90%E6%95%B0%E6%8D%AE/200%E5%B0%8F%E6%97%B6%E6%99%AE%E9%80%9A%E8%AF%9D%E6%89%8B%E6%9C%BA%E9%87%87%E9%9B%86%E8%AF%AD%E9%9F%B3%E6%95%B0%E6%8D%AE.zip?OSSAccessKeyId=LTAI2gYkXSt4KRmE&Expires=1870047600&Signature=zTjisbBJ2SELJeNPix2bvo2%2BMe8%3D

**Comment by wly112** [comment]
@xuchenxing 谢谢你反应的问题，是我们的失误，我们已将新的下载地址发送到了你的邮箱里，请注意查收！在进行语音识别实验中如遇到错误，请不吝指正。

**Comment by whaozl** [comment]
@wly112 @DatatangAI 您们好 www.openslr.org/resources/62/aidatatang_200zh.tgz的数据有划分好吗？

**Comment by wly112** [comment]
> @wly112 @DatatangAI 您们好 [www.openslr.org/resources/62/aidatatang_200zh.tgz](http://www.openslr.org/resources/62/aidatatang_200zh.tgz)
> 的数据有划分和更新好吗？

嗯嗯，现在openslr上是已经更新过的，可以直接使用啦

**Comment by whaozl** [comment]
太感谢啦 @wly112
