### ISSUE TITLE
local/aidatatang_train_lms2.sh: No such file or directory

### ISSUE THREAD

**Issue by fanlu** [datatang-ailab/aidatatang_200zh#3]
@DatatangAI 
there were some words missing problem when used local/aidatatang_train_lms.sh 
```
 compile-train-graphs --read-disambig-syms=data/lang/phones/disambig.int exp/mono/tree exp/mono/0.mdl data/lang/L.fst 'ark:sym2int.pl --map-oov 2 -f 2- data/lang/  words.txt < data/train/split100/100/text|' 'ark:|gzip -c >exp/mono/fsts.100.gz'
 sym2int.pl: replacing QQ号 with 2
 sym2int.pl: replacing C语言 with 2
 sym2int.pl: replacing QQ号 with 2
 ASSERTION_FAILED (compile-train-graphs[5.5.300~2-c326]:CompileGraphs():training-graph-compiler.cc:186) Assertion failed: (phone2word_fst.Start() != kNoStateId &&  "Perhaps you have words missing in your lexicon?")
```

**Comment by wly112** [comment]
> local/aidatatang_train_lms2.sh: No such file or directory
> 如果用local/aidatatang_train_lms.sh的话，又会少get_word_map.pl这个文件

是local/aidatatang_train_lms.sh。如果提示缺少get_word_map.pl文件，可能是没有正确安装kaldi_lm，重新安装一下kaldi_lm试试？
`tools/extra/install_kaldi_lm.sh`

**Comment by chen1399** [comment]
> > local/aidatatang_train_lms2.sh: No such file or directory
> > 如果用local/aidatatang_train_lms.sh的话，又会少get_word_map.pl这个文件
> 
> 是local/aidatatang_train_lms.sh。如果提示缺少get_word_map.pl文件，可能是没有正确安装kaldi_lm，重新安装一下kaldi_lm试试？
> `tools/extra/install_kaldi_lm.sh`

是的，万分感谢

**Comment by wly112** [comment]
> > > local/aidatatang_train_lms2.sh: No such file or directory
> > > 如果用local/aidatatang_train_lms.sh的话，又会少get_word_map.pl这个文件
> > 
> > 
> > 是local/aidatatang_train_lms.sh。如果提示缺少get_word_map.pl文件，可能是没有正确安装kaldi_lm，重新安装一下kaldi_lm试试？
> > `tools/extra/install_kaldi_lm.sh`
> 
> 是的，万分感谢

不客气哒~
