### ISSUE TITLE
prepare_dict.sh related problem

### ISSUE THREAD

**Issue by HuaChung** [datatang-ailab/aidatatang_200zh#6]
1. 为什么要在脚本中对文本数据进行中英文的分割，是数据集存在英文部分？还是为了能兼容两种类型词典？还是有其他原因？
2.  在prepare_dict.sh的脚本中开始部分提取了所有词到words.txt,其中对数据进行过滤
`| grep -v '\[LAUGHTER\]' | grep -v '\[NOISE\]' | grep -v '\[VOCALIZED-NOISE\]'`
数据中存在这些异常内容吗？

**Comment by wly112** [comment]
1.为了符合人们的日常用语习惯，数据集的语料中会存在常见的英文单词，故而处理文本时区分中英文。
2.数据不存在上述LAUGHTER, NOISE, VOCALIZED-NOISE标识
