### ISSUE TITLE
openslr的国内镜像上没有看到相关数据

### ISSUE THREAD

**Issue by sparkingarthur** [datatang-ailab/aidatatang_200zh#7]
http://cn-mirror.openslr.org上面没有编号62的数据。国外下过来速度比较慢。

**Comment by wly112** [comment]
国内镜像地址：http://cn-mirror.openslr.org/resources/62/aidatatang_200zh.tgz
 
非常抱歉没有及时看到消息，现在数据一直都可以从openslr上下载的，并且，数据也可以从https://www.datatang.com/webfront/opensource.html下载。
由于openslr国内镜像服务器的原因，所以数据下载有些慢，需要稍微多等一些时间。

**Comment by sparkingarthur** [comment]
> 国内镜像地址：http://cn-mirror.openslr.org/resources/62/aidatatang_200zh.tgz
> 
> 非常抱歉没有及时看到消息，现在数据一直都可以从openslr上下载的，并且，数据也可以从[https://www.datatang.com/webfront/opensource.html下载。](https://www.datatang.com/webfront/opensource.html%E4%B8%8B%E8%BD%BD%E3%80%82)
> 由于openslr国内镜像服务器的原因，所以数据下载有些慢，需要稍微多等一些时间。

谢谢，看到了。十分感谢。
