### ISSUE TITLE
实际运行结果与RESULTS有较大出入

### ISSUE THREAD

**Issue by Johe-cqu** [datatang-ailab/aidatatang_200zh#9]
您好， @wly112 
      很感谢您能分享200hours的数据以及训练代码。
      我在运行该程序后发现结果与RESULTS有较大的出入，其中mono的cer为46.51%，tri5a的cer为19.74%。
      我完全按照您的recipe运行，但是目录下的utils和steps替换成了wsj目录下的utils和steps的link。请问是否是该更改导致出入较大？还有哪里我需要注意吗？
                                                                                                                谢谢

**Comment by wly112** [comment]
> 您好， @wly112
> 很感谢您能分享200hours的数据以及训练代码。
> 我在运行该程序后发现结果与RESULTS有较大的出入，其中mono的cer为46.51%，tri5a的cer为19.74%。
> 我完全按照您的recipe运行，但是目录下的utils和steps替换成了wsj目录下的utils和steps的link。请问是否是该更改导致出入较大？还有哪里我需要注意吗？
> 谢谢

谢谢，每次训练得到的识别率都不会完全一样，您得到略低的识别率应该不是软连接的更改引起的，您可以试试其他的语音特征或调参来提升识别率。

**Comment by Johe-cqu** [comment]
拉取了一个新版本的kaldi重新训练后结果正常。
